<?php

return [
    'app' => [
        // styles
        'vendor/bootstrap/css/bootstrap.min.css',
        'vendor/jquery-ui/css/jquery-ui-1.10.1.custom.min.css',
        'vendor/swiper/css/swiper-3.2.5.min.css',
        'vendor/dialog/css/dialog.css',
        'vendor/zyupload/css/zyUpload.css',
        'vendor/mobile-select-area/css/mobile-select-area.css',
        'vendor/layer/mobile/need/layer.css',
        'vendor/wechat/style/weui.min.css',
        'fonts/iconfont.css',
        'css/ectouch.css',
        // script
        'vendor/common/jquery.min.js',
        'vendor/swiper/js/swiper-3.2.5.min.js',
        'vendor/common/jquery.infinite.js',
        'vendor/common/jquery.json.js',
        'vendor/common/template.js',
        'vendor/common/validform.js',
        'vendor/common/ap.js',
        'vendor/bootstrap/js/bootstrap.min.js',
        'vendor/layer/mobile/layer.m.js',
        'vendor/dialog/js/dialog.js',
        'vendor/jquery-ui/js/jquery-ui-1.10.1.custom.min.js',
        'vendor/jquery-ui/js/jquery.ui.touch-punch.min.js',
        'vendor/scrollup/jquery.scrollUp.min.js',
        'vendor/mobile-select-area/js/mobile-select-area.js',
        'vendor/parabola/parabola.js',
        'vendor/wechat/js/weui.min.js',
        'vendor/ecshop/common.js',
        'vendor/ecshop/shopping_flow.js',
        'vendor/ecshop/region_goods.js',
        'vendor/ecshop/lefttime.js',
        'vendor/ecshop/sms.js',
        'js/ectouch.js',
        'js/fastclick.js',
        'vendor/common/jquery.form.js',
        'vendor/common/jquery.time.js',
    ],
    'console' => [
        // styles
        '../../'.ADMIN_PATH.'/css/main.css',
        '../../'.ADMIN_PATH.'/css/font-awesome.min.css',
        '../../'.ADMIN_PATH.'/css/perfect-scrollbar.min.css',
        '../../'.ADMIN_PATH.'/css/purebox.css',
        '../../'.ADMIN_PATH.'/js/jquery-ui/jquery-ui.min.css',
        '../../js/calendar/calendar.min.css',
        '../../'.ADMIN_PATH.'/js/spectrum-master/spectrum.css',
        'css/console_style.css',
        // script
        'vendor/common/jquery.min.js',
        'vendor/layer/layer.js',
        'vendor/bootstrap/js/bootstrap.min.js',
    ],
    'wechat' => [
        // styles
        'vendor/bootstrap/css/bootstrap.min.css',
        'vendor/font-awesome/css/font-awesome.min.css',
        'vendor/fancybox/jquery.fancybox.css',
        'css/console_wechat.css',
        'fonts/wechat/iconfont.css',
        // script
        'vendor/common/jquery.min.js',
        'vendor/layer/layer.js',
        'vendor/bootstrap/js/bootstrap.min.js',
        'vendor/fancybox/jquery.fancybox.js',
        'vendor/common/jquery.form.js',
    ],
    'crowd_funding' => [
        // styles
        'vendor/swiper/css/swiper-3.2.5.min.css',
        'vendor/dialog/css/dialog.css',
        'vendor/mobile-select-area/css/mobile-select-area.css',
        'fonts/iconfont.css',
        'css/crowd_funding.css',
        // script
        'vendor/common/jquery.min.js',
        'vendor/common/jquery.json.js',
        'vendor/swiper/js/swiper-3.2.5.min.js',
        'vendor/common/jquery.infinite.js',
        'vendor/common/template.js',
        'vendor/common/ap.js',
        'vendor/dialog/js/dialog.js',
        'vendor/mobile-select-area/js/mobile-select-area.js',
        'vendor/ecshop/common.js',
        'vendor/ecshop/shopping_flow.js',
        'vendor/ecshop/region_goods.js',
        'js/crowd_funding.js',
    ],
    'team' => [
        // styles
        'vendor/bootstrap/css/bootstrap.min.css',
        'vendor/font-awesome/css/font-awesome.min.css',
        'vendor/fancybox/jquery.fancybox.css',
        'css/console_team.css',
        'vendor/layer/mobile/need/layer.css',
        // script
        'vendor/common/jquery.min.js',
        'vendor/bootstrap/js/bootstrap.min.js',
        'vendor/fancybox/jquery.fancybox.js',
        'vendor/common/validform.js',
        'vendor/layer/mobile/layer.m.js',
    ]
];
