DELETE FROM `{pre}touch_nav`;
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '店铺街', 1, 1, 0, 'index.php?m=store', 'top', 'store.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '品牌街', 1, 2, 0, 'index.php?m=brand', 'top', 'brand.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '促销活动', 1, 3, 0, 'index.php?m=activity', 'top', 'activity.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '最新团购', 1, 4, 0, 'index.php?m=groupbuy', 'top', 'groupbuy.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '积分换购', 1, 5, 0, 'index.php?m=exchange', 'top', 'exchange.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '微社区', 1, 6, 0, 'index.php?m=circle', 'top', 'community.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`) VALUES ('', 0, '微筹', 1, 7, 0, 'index.php?m=crowd_funding', 'top', 'crowd_funding.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '拍卖活动', 1, 8, 0, 'index.php?m=auction', 'top', 'auction.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '超值礼包', 1, 9, 0, 'index.php?m=package', 'top', 'package.png');
INSERT INTO `{pre}touch_nav` (`ctype`, `cid`, `name`, `ifshow`, `vieworder`, `opennew`, `url`, `type`, `pic`)VALUES ('', 0, '专题汇', 1, 10, 0, 'index.php?m=topic', 'top', 'topic.png');